### ISSUE TITLE
Failed to create eks node group

### ISSUE THREAD

**Issue by nicolas-gagnon** [lightspin-tech/eks-creation-engine#6]
Im receive this error during the deployment
Error encountered: Waiter NodegroupActive failed: Waiter encountered a terminal failure state: For expression "nodegroup.status" we matched expected path: "CREATE_FAILED"

![image](https://user-images.githubusercontent.com/59853744/155594441-fc0c53ad-4357-4def-846c-21ad16705949.png)

**Comment by jonrau-lightspin** [comment]
Hey there @nicolas-gagnon, firstly I'll take a look at extending the Waiter if I can just in case.

The error returned from the Waiter is typically a waste of time, but when the Nodegroups time out after that long there are a few issues that can cause it.

- **Networking**: ECE is meant to setup in Private Subnets, though it should work in a Public Subnet too, that said if you have blackholed or deleted routes that could be an issue. Review your Route Table, Routes to the NATGW & IGW, and Subnet Associations.

- **Capacity**: You're in us-east-1 so that should not be a problem, but some regions have a finite amount of resources per AZ for EKS. This has improved but can happen

- **AMI ID**: If you provided an AMI and did not use the `SSM` default value, if it was missing EKS/K8s/Docker dependencies installation can fail

- **Identity**: I can see that the role "NodegroupServiceRoleForEKS" already existed. That is the default name that I provide in the CLI, but if it was created before by something else without the proper permissions it may have led to an issue

Are you using the latest version of ECE? I had a bug in the past that the Nodegroup IAM Role was not written to cache and would not delete I was also missing SSM permissions which should not be an issue however.

**Comment by jonrau-lightspin** [comment]
@nicolas-gagnon I am closing this issue. Feel free to re-open if you still have issues.

**Comment by KatTraxler** [comment]
HI All.  I'm encountering this issue as well. I can say that:
Networking: Providing 2 standard, private subnets in different AZs (us-east-1). I reviewed the route tables for anything unusual.
AMI ID: Using the default
Identity:  I've attempted both with using the default named Role and a providing a custom NodeGroup Role Name.  Experience the same failure to create NodeGroups either way.  
Interestingly enough, I also experience failures with the kms.put_key_policy try block.  The script says I have an invalid ARN?  To bypass that, I have hardcoded a preexisting KMS key and commented out failed attempt to put key policy.
